### ISSUE TITLE
Access Mamba via Miniconda installation

### ISSUE THREAD

**Issue by dgwyer** [fastai/fastsetup#40]
@jph00 Thanks for the recent update to [`setup-conda.sh`](https://github.com/fastai/fastsetup/commit/2354ea6b7de2fc876941f29378f2034ee1ca8544). I just ran the script in Windows 11 and it istalled Miniconda perfectly!

However, I don't think this installer includes Mamba by default? May I ask what your workflow is, using the new `setup-conda.sh` script?

Do you just use Conda now, or do you install Mamba separately? If so I'm unsure what's the best way to do this. What commands would you recommend running after `setup-conda.sh` has finished?

I'm pretty new to this so would love to get the steps working correctly. I'm currently writing up my experiences from the [Live coding 1 video](https://www.youtube.com/watch?v=56sIyFjihEc) so I can share with others.

**Comment by dgwyer** [comment]
Ah, I see it's because Miniconda3 (i.e. Conda) now supports libmamba solver, so using Conda is just as fast as Mamba now.

https://twitter.com/AntreasAntonio/status/1697588723787993326

**Comment by jph00** [comment]
Yes exactly! :D
